on: push

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        working: [".", "test-project"]

    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 14
      - run: yarn --frozen
        working-directory: ${{ matrix.working }}
      - run: yarn build
        working-directory: ${{ matrix.working }}
      - run: yarn test
        working-directory: ${{ matrix.working }}
      # - name: TypeScript Error Reporter
      #   uses: andoshin11/typescript-error-reporter-action@v1.0.2
